

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
import os, datetime, json, pickle, psutil, zipfile, socket, random, importlib
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def TimeStamp(start='', sep='', end=''): 
    return (start + datetime.datetime.strftime(datetime.datetime.now(), 
    sep.join(["%Y", "%m", "%d", "%H", "%M", "%S", "%f"])) + end)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class TaskStatus:
    # Status updates while offloading and executing task are sent to UE that generate it
    SENT =      'ts-sent'       # task was generated by UE and pushed to OM
    RECEIVED =  'ts-recv'       # task was received by OM
    OFFLOADED = 'ts-offloaded'  # task was sent to CN after selecting one using offloading policy
    QUEUED =    'ts-queued'     # task was received by CN and waits in its execution queue
    STARTED =   'ts-started'    # task started execution by CN
    FINISH =    'ts-finished'   # task finished execution by CN
    @staticmethod
    def TS(): return TimeStamp(sep=":")
    @staticmethod
    def ID(start): return TimeStamp(start=start)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class OpsConfig: 
    # Directories used by operational code
    NODES_DIR_NAME =    "NODES"
    QUEUE_DIR_NAME =    "QUEUE"
    TRACES_DIR_NAME =   "TRACES"
    STATES_DIR_NAME =   "STATES"
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class FileConfig:
    EXE_NAME =      "cosim.exe"
    EYE_NAME =      "cosim.eye"
    PIE_NAME =      "cosim.pie"
    TASK_EXT =      ".py"           # executable file extension
    TASK_OUT =      "output.txt"    # used by CN to log stdout and stderr for subprocess
    ZIP_NAME =      "task.zip"      # used by UE and CN to identify zip file to extrace tasks data from
    META_NAME =     "meta.json"     # used by UE to save task information when generating a task
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def Scan(path, exclude_hidden=False, include_size=False, include_extra=False):
    #if not os.path.exists(path): return []
    r""" Scans a directory using os.scandir call 
            returns a list of 6 or 9 tuple (name, path, isdir, isfile, islink, size, parent, fname, ext) """
    def SplitName(f):
        i = f.rfind('.')
        return (f, None) if i<0 else (f[0:i], f[i+1:])
    if exclude_hidden:  
        if include_size: 
            if include_extra:   return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), x.stat().st_size, os.path.dirname(os.path.abspath(x.path)), *SplitName(x.name)) for x in os.scandir(path) if not x.name.startswith(".")]
            else:               return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), x.stat().st_size) for x in os.scandir(path) if not x.name.startswith(".")]

        else:            
            if include_extra:   return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), -1              , os.path.dirname(os.path.abspath(x.path)), *SplitName(x.name)) for x in os.scandir(path) if not x.name.startswith(".")]
            else:               return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), -1              ) for x in os.scandir(path) if not x.name.startswith(".")]
    else:
        if include_size: 
            if include_extra:   return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), x.stat().st_size, os.path.dirname(os.path.abspath(x.path)), *SplitName(x.name)) for x in os.scandir(path)]
            else:               return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), x.stat().st_size) for x in os.scandir(path)]
        else:
            if include_extra:   return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), -1              ,os.path.dirname(os.path.abspath(x.path)), *SplitName(x.name)) for x in os.scandir(path)]
            else:               return [(x.name, os.path.abspath(x.path), x.is_dir(), x.is_file(), x.is_symlink(), -1              ) for x in os.scandir(path)]
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def ReScan(path, exclude_hidden=False, include_size=False, include_extra=False):
    r""" Recursively Scans a directory using os.scandir """
    res = []
    pending = [path]
    while pending:
        try:
            ls = Scan(pending.pop(0), exclude_hidden=exclude_hidden, include_size=include_size, include_extra=include_extra)
            for l in ls: # name, path, isdir, isfile, islink, size, parent, (fname, ext)
                res.append(l)
                if l[2]: (pending.append(l[1]) if not l[4] else None)
        except: pass
    return res
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def Zipped(src_path, zip_path):
    src_path = os.path.abspath(src_path)
    parent_dir = os.path.dirname(src_path)
    #base_name = os.path.basename(src_path)
    #zip_path = os.path.join(parent_dir, zip_name)
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(src_path):
            # preserve empty directories too
            rel_root = os.path.relpath(root, parent_dir)
            zf.write(root, rel_root)
            for fname in files:
                full_path = os.path.join(root, fname)
                rel_path = os.path.relpath(full_path, parent_dir)
                zf.write(full_path, rel_path)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def UnZipped(zip_path, target_path):
    with zipfile.ZipFile(zip_path, "r") as zf: zf.extractall(target_path)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def RandomChoice(obj): return obj[random.randint(0, len(obj)-1)]
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def SetupLogging(logging, logfile, verbose, sep=" "):
    LOGFILE = None
    if logfile and verbose: 
        try: # Set up logging to a file # also output to the console
            LOGFILE = logfile
            format=f'%(asctime)s{sep}%(message)s'
            logging.basicConfig(filename=LOGFILE, level=logging.INFO, format=format)
            console_handler = logging.StreamHandler()
            console_handler.setLevel(logging.INFO)
            formatter = logging.Formatter(format)
            console_handler.setFormatter(formatter)
            logger = logging.getLogger()
            logger.addHandler(console_handler)
        except: exit(f'[!] Logging could not be setup at {LOGFILE}')
    # ------------------------------------------------------------------------------------------
    if not verbose: sprint = lambda m: None
    else:
        if LOGFILE is None: sprint = lambda m: print(m)
        else: sprint = lambda m: logging.info(m) 
    # ------------------------------------------------------------------------------------------

    return sprint
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def ImportCustomModule(python_file, python_object, do_initialize, **kwargs):
    r""" Import a custom module from a python file and optionally initialize it """
    cpath = os.path.abspath(python_file)
    failed=""
    if os.path.isfile(cpath): 
        try: 
            # from https://stackoverflow.com/questions/67631/how-can-i-import-a-module-dynamically-given-the-full-path
            cspec = importlib.util.spec_from_file_location("", cpath)
            cmodule = importlib.util.module_from_spec(cspec)
            cspec.loader.exec_module(cmodule)
            success=True
        except: success=False #exit(f'[!] Could import user-module "{cpath}"')
        if success: 
            if python_object:
                try:
                    cmodule = getattr(cmodule, python_object)
                    if do_initialize:  cmodule = cmodule(**kwargs)
                except:         cmodule, failed = None, f'[!] Could not import object {python_object} from module "{cpath}"'
        else:                   cmodule, failed = None, f'[!] Could not import module "{cpath}"'
    else:                       cmodule, failed = None, f"[!] File Not found @ {cpath}"
    return cmodule, failed
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class Kio:
    @staticmethod
    def LoadJSON(path):
        with open(path, 'r') as f: obj = json.load(f)
        return obj
    @staticmethod
    def SaveJSON(path, obj, indent=4):
        with open(path, 'w') as f: json.dump(obj, f, indent=indent)
    @staticmethod
    def LoadPICK(path):
        with open(path, 'rb') as f: obj = pickle.load(f)
        return obj
    @staticmethod
    def SavePICK(path, obj):
        with open(path, 'wb') as f: pickle.dump(obj, f)
    @staticmethod
    def LoadTEXT(path):
        with open(path, 'r') as f: obj = f.read()
        return obj
    @staticmethod
    def SaveTEXT(path, obj):
        with open(path, 'w') as f: f.write(obj)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class FixStateInfo:

    @staticmethod
    def CPU():
        physical_cores = psutil.cpu_count(logical=False)
        logical_cpus = psutil.cpu_count(logical=True)

        freq = psutil.cpu_freq()
        min_frequency_mhz = None
        max_frequency_mhz = None
        current_frequency_mhz = None

        if freq is not None:
            min_frequency_mhz = freq.min
            max_frequency_mhz = freq.max
            current_frequency_mhz = freq.current

        return {
            "physical_cores": physical_cores,
            "logical_cpus": logical_cpus,
            "min_frequency_mhz": min_frequency_mhz,
            "max_frequency_mhz": max_frequency_mhz,
            "current_frequency_mhz": current_frequency_mhz,
        }

    @staticmethod
    def MEM():
        mem = psutil.virtual_memory()
        swap = psutil.swap_memory()

        mem_total = mem.total
        swap_total = swap.total

        return {
            "mem_total": mem_total,
            "swap_total": swap_total,
        }

    @staticmethod
    def NET():
        interfaces = {}

        addresses = psutil.net_if_addrs()
        stats = psutil.net_if_stats()

        for interface_name in addresses:
            addr_list = []

            for addr in addresses[interface_name]:
                addr_list.append({
                    "family": str(addr.family),
                    "address": addr.address,
                    "netmask": addr.netmask,
                    "broadcast": addr.broadcast,
                    "ptp": addr.ptp,
                })

            interface_stats = None

            if interface_name in stats:
                stat = stats[interface_name]

                interface_stats = {
                    "isup": stat.isup,
                    "duplex": str(stat.duplex),
                    "speed": stat.speed,
                    "mtu": stat.mtu,
                    "flags": stat.flags,
                }

            interfaces[interface_name] = {
                "addresses": addr_list,
                "stats": interface_stats,
            }

        return interfaces

    @staticmethod # OM
    def ALL(**kwargs): return {**__class__.CPU(), **__class__.MEM(), **kwargs, 'ts':TimeStamp(sep='-'),}
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class VarStateInfo:

    @staticmethod
    def CPU(interval=1):
        cpu_percent = psutil.cpu_percent(interval=interval)
        #cpu_percent_per_cpu = psutil.cpu_percent(interval=interval, percpu=True)

        #cpu_times = dict(psutil.cpu_times()._asdict())

        #cpu_times_per_cpu = []
        #for item in psutil.cpu_times(percpu=True):
        #    cpu_times_per_cpu.append(dict(item._asdict()))

        #cpu_stats = dict(psutil.cpu_stats()._asdict())

        load1, load5, load15 = psutil.getloadavg()
        #load_average = [load1, load5, load15]

        freq = psutil.cpu_freq()
        current_frequency_mhz = None

        if freq is not None:
            current_frequency_mhz = freq.current

        return {
            "cpu_percent": cpu_percent,
            #"cpu_percent_per_cpu": cpu_percent_per_cpu,
            #"cpu_times": cpu_times,
            #"cpu_times_per_cpu": cpu_times_per_cpu,
            #"cpu_stats": cpu_stats,
            "load_average_1": load1,
            "load_average_5": load5,
            "load_average_15": load15,
            "current_frequency_mhz": current_frequency_mhz,
        }

    @staticmethod
    def MEM(): return {
            "mem": dict( psutil.virtual_memory()._asdict()),
            "swap": dict(psutil.swap_memory()._asdict()),
        }

    @staticmethod
    def NET():
        network_io = dict(psutil.net_io_counters()._asdict())

        network_io_per_interface = {}

        for interface_name, counters in psutil.net_io_counters(pernic=True).items():
            network_io_per_interface[interface_name] = dict(counters._asdict())

        return {
            "network_io": network_io,
            "network_io_per_interface": network_io_per_interface,
        }
    
    @staticmethod # OM
    def ALL(**kwargs): return {**__class__.CPU(), **__class__.MEM(), **kwargs, 'ts':TimeStamp(sep='-'),}
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def ValidatePath(base, other):
    target = os.path.abspath(os.path.join(base, other))
    rel = os.path.relpath(target, base)
    if rel.startswith(os.pardir + os.sep) or rel == os.pardir: return None
    else: return target
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def DirectoryListing(dirpath, exclude_hidden=False): return {name:dict(path=path, size=size, itype=( ("📁" if isdir else "") + ("🗒️" if isfile else "") + ("🔗" if islink else "") )) for name, path, isdir, isfile, islink, size in ReScan(dirpath, exclude_hidden=exclude_hidden, include_size=True, include_extra=False)}
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def GetIP():
    ips = []
    for iface, addrs in psutil.net_if_addrs().items():
        for addr in addrs:
            if addr.family == socket.AF_INET: ips.append(addr.address)
    return ips
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class Infinity: 
    # emulates infinity with comparision operators < <=, >, >=, ==
    #   +inf    =  Infinity(1)
    #   -inf    =  Infinity(-1)
    # emulates Empty and Universal sets with 'in' keyword
    #   Universal Set (everything) = Infinity(1)
    #   Null/Empty Set (nothing) = Infinity(-1)

    def __init__(self, sign=1) -> None: self.sign = (sign>=0) # has positive
    
    def __gt__(self, other): return self.sign       # +inf is greater than everything / -inf is greater than nothing
    def __ge__(self, other): return self.sign       

    def __lt__(self, other): return not self.sign   # -inf is less than everything    / +inf is less than nothing
    def __le__(self, other): return not self.sign

    def __eq__(self, other): return False           # inf is not equal to anything, not even itself

    def __contains__(self, x): return self.sign     # universal set contains everything (always true), empty set contains nothing (always false)
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

